function [fitresult, gof] = createFit(Lq, u)
%CREATEFIT(LQ,U)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : Lq
%      Y Output: u
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Jul-2022 16:17:28


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( Lq, u );

% Set up fittype and options.
ft = fittype( 'gauss6' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0 -Inf -Inf 0];
opts.StartPoint = [15077.5550064627 465.566037735849 6.30677067943647 11377.3757741368 453.559176672384 8.10847340427965 6469.23235520224 494.682675814751 10.7793278705294 5942.02513857349 568.825042881647 14.6735949757782 5931.88650806424 438.250428816467 16.7336950503892 5578.29762131704 477.572898799314 17.4417740768851];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );
% h = plot( fitresult, xData, yData );
% legend( h, 'u vs. Lq', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'Lq', 'Interpreter', 'none' );
% ylabel( 'u', 'Interpreter', 'none' );
% grid on


