function HgNeOriel6034 = importlines(filename, dataLines)
%IMPORTFILE7 Import data from a text file
%  HGNEORIEL6034 = IMPORTFILE7(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a string
%  array.
%
%  HGNEORIEL6034 = IMPORTFILE7(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  HgNeOriel6034 = importfile7("C:\Users\rdatta\Dropbox (MIT)\PUFFIN\Data\MARZ\SVS\svs5\HgNeOriel6034.txt", [1, 19]);
%
%  See also READMATRIX.
%
% Auto-generated by MATLAB on 30-Aug-2022 13:23:10

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Hg", "VarName2", "VarName3"];
opts.VariableTypes = ["string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Hg", "VarName2", "VarName3"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Hg", "VarName2", "VarName3"], "EmptyFieldRule", "auto");

% Import the data
HgNeOriel6034 = readmatrix(filename, opts);

end