function AlII1 = importfile3(filename, startRow, endRow)
%IMPORTFILE3 Import numeric data from a text file as a matrix.
%   ALII1 = IMPORTFILE3(FILENAME)
%   Reads data from text file FILENAME for the default selection.
%
%   ALII1 = IMPORTFILE3(FILENAME, STARTROW, ENDROW)
%   Reads data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   AlII1 = importfile3('Al-II.csv', 7, 152);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2022/07/13 17:17:14

%% Initialize variables.
if nargin<=2
    startRow = 7;
    endRow = 152;
end

%% Format for each line of text:
%   column1: text (%s)
%	column5: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%16s%*3*s%*16*s%*3s%7s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this code. If an error occurs for a different file, try regenerating the code from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Remove white space around all cell columns.
dataArray{1} = strtrim(dataArray{1});
dataArray{2} = strtrim(dataArray{2});

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post processing code is included. To generate code which works for unimportable data, select unimportable cells in a file and regenerate the script.

%% Create output variable
AlII1 = [dataArray{1:end-1}];
