function [VarName1,VarName5] = importfile2(filename, startRow, endRow)
%IMPORTFILE2 Import numeric data from a text file as column vectors.
%   [VARNAME1,VARNAME5] = IMPORTFILE2(FILENAME)
%   Reads data from text file FILENAME for the default selection.
%
%   [VARNAME1,VARNAME5] = IMPORTFILE2(FILENAME, STARTROW, ENDROW)
%   Reads data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   [VarName1,VarName5] = importfile2('Al-II.csv',7, 152);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2022/07/13 17:11:59

%% Initialize variables.
if nargin<=2
    startRow = 7;
    endRow = 152;
end

%% Format for each line of text:
%   column1: categorical (%C)
%	column5: categorical (%C)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%16C%*3*s%*16*s%*3C%7C%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this code. If an error occurs for a different file, try regenerating the code from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post processing code is included. To generate code which works for unimportable data, select unimportable cells in a file and regenerate the script.

%% Allocate imported array to column variable names
VarName1 = dataArray{:, 1};
VarName5 = dataArray{:, 2};


