function Hg = importfileHg(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  HG = IMPORTFILE1(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as a string array.
%
%  HG = IMPORTFILE1(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  Hg = importfile1("C:\Users\rdatta\Dropbox (MIT)\PUFFIN\Data\Other\Lines\Hg.txt", [2, Inf]);
%
%  See also READMATRIX.
%
% Auto-generated by MATLAB on 18-Jul-2022 14:00:31

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "sp_num", "obs_wl_airnm", "intens", "Var5", "Var6", "Var7", "Var8", "Var9"];
opts.SelectedVariableNames = ["sp_num", "obs_wl_airnm", "intens"];
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "sp_num", "obs_wl_airnm", "intens", "Var5", "Var6", "Var7", "Var8", "Var9"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "sp_num", "obs_wl_airnm", "intens", "Var5", "Var6", "Var7", "Var8", "Var9"], "EmptyFieldRule", "auto");

% Import the data
Hg = readmatrix(filename, opts);

end